services:
  backend:
    build: ./server
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend